accounts/urls.py
from django.conf.urls import url
from.import views


app_name= 'accounts'

urlpatterns = [
    url(r'^signup/$',views.signup_view,name="signup"),
    url(r'^$',views.login_view,name="login"),
    url(r'^logout/$',views.logout_view,name="logout"),

]

ikigai/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    url('admin/', admin.site.urls),
    url('',include('accounts.urls')),
    url(r'^purpose/',include('purpose.urls')),
]

purpose/urls.py
from django.conf.urls import url
from django.contrib import admin
from.import views

app_name= 'purpose'

urlpatterns = [
    url(r'^$',views.section,name="home"),
    url(r'^users$',views.users,name="users"),
    url(r'^delete/list/(?P<pk>[\w-]+)$', views.delete, name='delete'),
    url(r'^updatelist/(?P<pk>[\w-]+)$', views.edit, name='update'),
  	url(r'^retrivelist/(?P<pk>[\w-]+)$', views.retrieve_user_list, name='retrive_user_list'),

    #url(r'^$',views.login_view,name="login"),
    #url(r'^logout/$',views.logout_view,name="logout"),

]

accounts/models.py
from django.db import models

  		

purpose/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Section(models.Model):
    name=models.CharField(max_length=250)

    def __str__(self):
        return self.name

class list(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    name=models.TextField()
    section=models.ForeignKey('Section',on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name)+" by"+str(self.user.username)


accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User






class UserSignUpForm(UserCreationForm):
    full_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')



    class Meta:
        model = User
        fields = ('email','username', 'password1', 'password2' )

    def save(self, commit=True):
        user = super(UserSignUpForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

purpose/forms.py
from django import forms
from .models import *
class AddList(forms.ModelForm):
    class Meta:
        model=list
        fields=['name']

class UpdateList(forms.ModelForm):
    class Meta:
        model=list
        fields=['name','section']

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout,authenticate
from .forms import UserSignUpForm
from django.http import HttpResponseRedirect,HttpResponse

# Create your views here.
def signup_view(request):
    if request.method =='POST':
        form=UserSignUpForm(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            user.is_active=False
            user.save()

            login(request,user)
            return redirect('purpose:home')
    else:
        form=UserSignUpForm()
    return render(request,'accounts/signup.html',{'form':form,})


def login_view(request):
    if request.method =='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            user=form.get_user()
            login(request,user)
            if'next'in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('purpose:home')
    else:
        form= AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})


def logout_view(request):
    if request.method=='POST':
        logout(request)
        return redirect('accounts:login')

purpose/views.py
from django.shortcuts import render,redirect
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

# Create your views here.


@login_required
def section(request):
    u=User.objects.all()
    s=Section.objects.all()
    t=None
    if request.method == 'POST':
        x=request.POST.get('list')
        y = request.POST
        l=None
        for key,value in y.items():
                if value== 'Add':
                    l=key

        t= Section.objects.get(name=l)
        m=list.objects.create(name=x,user=request.user,section=t)
    p=[]
    q=[]
    r=[]
    w=[]
    passion=set()
    mission=set()
    profession=set()
    vocation=set()

    for i in list.objects.filter(user=request.user,section=s[0]):
        p.append(i.name)

    for i in list.objects.filter(user=request.user,section=s[1]):
        q.append(i.name)
    for i in list.objects.filter(user=request.user,section=s[2]):
        r.append(i.name)
    for i in list.objects.filter(user=request.user,section=s[3]):
        w.append(i.name)
   
      
    passion=set(p).intersection(set(q))
    mission=set(p).intersection(set(w))
    profession=set(r).intersection(set(q))
    vocation=set(w).intersection(set(r))

    print(passion)
    print(mission)
    print(profession)
    print(vocation)
    purpose = []
    for i in passion:
        purpose.append(i)
    for i in mission:
        purpose.append(i)
    for i in profession:
        purpose.append(i)
    for i in vocation:
        purpose.append(i)

    t=list.objects.all().filter(user=request.user).order_by('-id')
    return render(request,'purpose/section.html',{'s':s,'t':t,'u':u,'purpose':purpose})
@login_required
def edit(request,pk):

    l=list.objects.get(pk=pk)
    form=UpdateList(instance=l)
    if request.method=="POST":
        form=UpdateList(request.POST,instance=l)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.user=request.user

            instance.save()
            return redirect('purpose:home')
        else:
            form=UpdateList(instance=pk)
    return render(request,'purpose/update.html',{'form':form})
@login_required
def users(request):
    u=User.objects.exclude(email=request.user.email)
    return render(request,'purpose/users.html',{'u':u})
@login_required
def retrive_by_user(request,pk):



    l=list.objects.all().filter(user=request.user)

    return render(request,'purpose/retrive.html',{'l':l,'k':k})
@login_required
def retrieve_user_list(request,pk):

    s=Section.objects.all()
   
    u=User.objects.get(pk=pk)
    t=list.objects.filter(user=u)
    return render(request,'purpose/retrive.html',{'s':s,'t':t})

@login_required
def delete(request,pk):
    l=list.objects.get(pk=pk).delete()
    return redirect('purpose:home')


accounts/templates/accounts/login.html
{% extends 'base.html'%}



{% block content %}
  <div class="parallax-signup" data-parallax="scroll" data-z-index="1" data-image-src="/static/2.jpg">
    <br><br><br>
    <h1 class = "para-signup" align = "center">LOG IN</h1>
    <form class="site-form"  method="post">
      {%csrf_token%}
      {{form}}
      {% if request.GET.next %}
        <input type="hidden"name="next"value="{{request.GET.next}}">
      {% endif %}
      <input type="submit"value="Login">
    </form>
  </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html'%}



{% block content %}
    <div class="parallax-signup" data-parallax="scroll" data-z-index="1" data-image-src="/static/2.jpg">
    <br>
    <br>
    <h1 class="para-signup" align = "center">SIGN UP</h1>
    <form class="site-form-signup"  method="post">
        {%csrf_token%}
      {{form}}
      <input type="submit"value="signup">
    </form>
  </div>
{% endblock %}

purpose/templates/purpose/create.html

{% extends 'base.html'%}



{% block content %}
  <body>
    <form class="" method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" value="submit" name="submit">
    </form>



  {% endblock %}

purpose/templates/purpose/retrive.html


{% extends 'base.html'%}



{% block content %}
<div class="container">
  <div class="row">
    {% for i in s %}
     <div class="col-md-3 col-lg-3">
      {% if forloop.counter == 1 %}
    <div class="card-deck bg-info card border-dark mb-3" >
    
      {% elif forloop.counter == 2 %}
      <div class="card-deck bg-primary card border-dark mb-3" >
        {% elif forloop.counter == 3 %}
         <div class="card-deck bg-secondary card border-dark mb-3" >
        {% else %} 
        <div class="card-deck bg-danger card border-dark mb-3" >
          {%endif %}
      <div class="card-body text-center">
         <h4 class="card-title">{{i.name}}</h4>
        
      <ul class="list-group list-group-flush bg-info ">
         
          {% for j in t %}
            {% if j.section.name == i.name %}
              <li class="list-group-item"><table><tr><td>{{j.name}}</td>
            </tr>
          </table>
        </li>
            {% endif %}
             {% empty %}
            <li class="list-group-item"><h3>No List Has Been Posted</li>
    
            {% endfor %}

      </ul>
     </div >
    </div >
  </div>
    {% endfor %}
  </div>
</div>
 




{% endblock %}

purpose/templates/purpose/section.html


{% extends 'base.html'%}



{% block content %}
<div class="container">
  <div class="row">
    <center><h3 style ="color:red;">Your purpose should be combination of {% for i in purpose %} , {{i}}  {% endfor %}</h3></center>
    {% for i in s %}
     <div class="col-md-3 col-lg-3">
      {% if forloop.counter == 1 %}
    <div class="card-deck bg-info card border-dark mb-3" >
    
      {% elif forloop.counter == 2 %}
      <div class="card-deck bg-primary card border-dark mb-3" >
        {% elif forloop.counter == 3 %}
         <div class="card-deck bg-secondary card border-dark mb-3" >
        {% else %} 
        <div class="card-deck bg-danger card border-dark mb-3" >
          {%endif %}
      <div class="card-body text-center">
         <h4 class="card-title">{{i.name}}</h4>
        
      <ul class="list-group list-group-flush bg-info ">
          <li class="list-group-item">
          <form class="" method="post">
            {% csrf_token %}
          <input type="text" name="list" required>
          <input type="submit" name="{{ i.name }}" value="Add">
        </form>
        </li>
          {% for j in t %}
            {% if j.section.name == i.name %}
              <li class="list-group-item"><table><tr><td>{{j.name}}</td>
              <td><a href="{% url 'purpose:update' j.pk %}">Update</a></td>
              <td><a href="{% url 'purpose:delete' j.pk %}">Delete</a></td>
            </tr>
          </table>
        </li>
            {% endif %}
            {% endfor %}

      </ul>
     </div >
    </div >
  </div>
    {% endfor %}
  </div>
</div>
    <br>
    <br>

    <br>
    <br>
   <center> <h3> Want to see the list of others users </h3>
      <a href="{% url 'purpose:users' %}">USER</a></center>




{% endblock %}

purpose/templates/purpose/update.html

{% extends 'base.html'%}



{% block content %}
  <body>
    <form class="" method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" value="submit" name="submit">
    </form>



  {% endblock %}

purpose/templates/purpose/users.html
{% extends 'base.html'%}



{% block content %}

<br>
<center>

    {% for i in u %}
    {{i.username}} {{i.email}} <a href="{% url 'purpose:retrive_user_list' i.pk %}">View List</a>

    <br>
    {% endfor %}

</center>

{% endblock %}

templates/base.html

{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <title>IKIGAI</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </head>

<body >

  <!--/ Nav Star /-->
  <nav class="navbar navbar-expand-sm bg-light justify-content-center">
    <div class="container">
    

      <div class="mx-auto order-0">
        <a class="navbar-brand mx-auto" href="#">IKIGAI</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
           {% if not user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:signup' %}">Register</a>
        </li>
        {% else %}
        <li class="nav-item ">

            <i class="fa fa-user" style="margin-right: 5px;"></i>Hello  {{ request.user.username}}
          </li>
          <li class="nav-item">
          <a class="nav-link">
            <form classs="logout_link" action ="{% url 'accounts:logout' %}" method="post">
                {% csrf_token %}
                <button type ="submit" class="btn btn-link navbar-btn">Logout</button>
             </form>
          </a>

      {% endif %}

        </ul>
    </div>



        </div>
</nav>
  <!--/ Nav End /-->




    <!--Navbar-->

<!--Navbar -->

            {% block content %}

          {% endblock %}



  </body>
</html>